export const FETCH_PRODUCT_REQUEST = "product/FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS = "product/FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAIL = "product/FETCH_PRODUCT_FAIL";