export const FETCH_PRODUCTS_REQUEST = "catalog/FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "catalog/FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "catalog/FETCH_PRODUCTS_FAIL";